/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tasks: Task;
    milestones: Milestone;
    notes: Note;
    spaces: Space;
    'shopping-rooms': ShoppingRoom;
    'shopping-items': ShoppingItem;
    expenses: Expense;
    photos: Photo;
    'inventory-items': InventoryItem;
    utilities: Utility;
    projects: Project;
    'quick-links': QuickLink;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    milestones: MilestonesSelect<false> | MilestonesSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    spaces: SpacesSelect<false> | SpacesSelect<true>;
    'shopping-rooms': ShoppingRoomsSelect<false> | ShoppingRoomsSelect<true>;
    'shopping-items': ShoppingItemsSelect<false> | ShoppingItemsSelect<true>;
    expenses: ExpensesSelect<false> | ExpensesSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    'inventory-items': InventoryItemsSelect<false> | InventoryItemsSelect<true>;
    utilities: UtilitiesSelect<false> | UtilitiesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'quick-links': QuickLinksSelect<false> | QuickLinksSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    property: Property;
    contacts: Contact;
  };
  globalsSelect: {
    property: PropertySelect<false> | PropertySelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  title: string;
  detail?: string | null;
  due?: string | null;
  assignee?: ('' | 'Justin' | 'Natalie') | null;
  phase: '0' | '1' | '2' | '3' | '4';
  done?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones".
 */
export interface Milestone {
  id: number;
  label: string;
  date: string;
  type: 'key' | 'deadline' | 'done';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  title?: string | null;
  body: string;
  author: 'Justin' | 'Natalie';
  space?: (number | null) | Space;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces".
 */
export interface Space {
  id: number;
  name: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopping-rooms".
 */
export interface ShoppingRoom {
  id: number;
  name: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopping-items".
 */
export interface ShoppingItem {
  id: number;
  name: string;
  room: number | ShoppingRoom;
  priority?: ('Must have' | 'Nice to have' | 'Someday') | null;
  status?: ('Need to buy' | 'Ordered' | 'Delivered' | 'Done') | null;
  store?: string | null;
  priceEst?: string | null;
  priceActual?: string | null;
  dims?: string | null;
  qty?: number | null;
  assignee?: ('' | 'Justin' | 'Natalie') | null;
  link?: string | null;
  image?: string | null;
  notes?: string | null;
  done?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses".
 */
export interface Expense {
  id: number;
  description: string;
  est?: string | null;
  actual?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  /**
   * Direct image URL. Or upload a file using the Media collection.
   */
  url?: string | null;
  media?: (number | null) | Media;
  caption?: string | null;
  category?:
    | (
        | 'Exterior'
        | 'Main Floor'
        | 'Kitchen'
        | 'Primary Bedroom'
        | "Ethan's Room"
        | "Elle's Room"
        | "Riley's Room"
        | 'Bathrooms'
        | 'Basement'
        | 'Pool & Outdoor'
        | 'Garage'
        | 'MLS'
        | 'Other'
      )
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-items".
 */
export interface InventoryItem {
  id: number;
  title: string;
  status?: ('Undecided' | 'Keep' | 'Sell' | 'Donate' | 'Trash') | null;
  owner?: ('Justin' | 'Natalie' | 'Both') | null;
  space?: (number | null) | Space;
  duplicate?: boolean | null;
  notes?: string | null;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utilities".
 */
export interface Utility {
  id: number;
  type: string;
  provider?: string | null;
  phone?: string | null;
  website?: string | null;
  account?: string | null;
  username?: string | null;
  cost?: string | null;
  status?: ('Not set up' | 'Transfer in progress' | 'Active' | 'Cancelled') | null;
  notes?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  category?:
    | (
        | 'Pool & Outdoor'
        | 'Landscaping'
        | 'Bedrooms'
        | 'Primary Bedroom'
        | 'Kitchen'
        | 'Bathrooms'
        | 'Basement'
        | 'Living Areas'
        | 'Exterior'
        | 'Other'
      )
    | null;
  priority?: ('before-move' | 'soon' | 'someday') | null;
  status?: ('planning' | 'progress' | 'complete') | null;
  costEst?: string | null;
  contractor?: string | null;
  notes?: string | null;
  done?: boolean | null;
  subtasks?:
    | {
        label: string;
        done?: boolean | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quick-links".
 */
export interface QuickLink {
  id: number;
  label: string;
  url: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'milestones';
        value: number | Milestone;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'spaces';
        value: number | Space;
      } | null)
    | ({
        relationTo: 'shopping-rooms';
        value: number | ShoppingRoom;
      } | null)
    | ({
        relationTo: 'shopping-items';
        value: number | ShoppingItem;
      } | null)
    | ({
        relationTo: 'expenses';
        value: number | Expense;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'inventory-items';
        value: number | InventoryItem;
      } | null)
    | ({
        relationTo: 'utilities';
        value: number | Utility;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'quick-links';
        value: number | QuickLink;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  detail?: T;
  due?: T;
  assignee?: T;
  phase?: T;
  done?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones_select".
 */
export interface MilestonesSelect<T extends boolean = true> {
  label?: T;
  date?: T;
  type?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  author?: T;
  space?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces_select".
 */
export interface SpacesSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopping-rooms_select".
 */
export interface ShoppingRoomsSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopping-items_select".
 */
export interface ShoppingItemsSelect<T extends boolean = true> {
  name?: T;
  room?: T;
  priority?: T;
  status?: T;
  store?: T;
  priceEst?: T;
  priceActual?: T;
  dims?: T;
  qty?: T;
  assignee?: T;
  link?: T;
  image?: T;
  notes?: T;
  done?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses_select".
 */
export interface ExpensesSelect<T extends boolean = true> {
  description?: T;
  est?: T;
  actual?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  url?: T;
  media?: T;
  caption?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-items_select".
 */
export interface InventoryItemsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  owner?: T;
  space?: T;
  duplicate?: T;
  notes?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utilities_select".
 */
export interface UtilitiesSelect<T extends boolean = true> {
  type?: T;
  provider?: T;
  phone?: T;
  website?: T;
  account?: T;
  username?: T;
  cost?: T;
  status?: T;
  notes?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  priority?: T;
  status?: T;
  costEst?: T;
  contractor?: T;
  notes?: T;
  done?: T;
  subtasks?:
    | T
    | {
        label?: T;
        done?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quick-links_select".
 */
export interface QuickLinksSelect<T extends boolean = true> {
  label?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property".
 */
export interface Property {
  id: number;
  address?: string | null;
  mlsNumber?: string | null;
  status?: ('Active' | 'Offer Accepted' | 'Under Contract' | 'Closed') | null;
  offerPrice?: number | null;
  listPrice?: number | null;
  sqft?: number | null;
  beds?: number | null;
  bathsFull?: number | null;
  bathsHalf?: number | null;
  annualTaxes?: number | null;
  listingDescription?: string | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  heroImages?:
    | {
        url: string;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  laName?: string | null;
  laTitle?: string | null;
  laPhone?: string | null;
  laEmail?: string | null;
  laNotes?: string | null;
  baName?: string | null;
  baTitle?: string | null;
  baPhone?: string | null;
  baEmail?: string | null;
  baNotes?: string | null;
  lenderName?: string | null;
  lenderTitle?: string | null;
  lenderPhone?: string | null;
  lenderEmail?: string | null;
  lenderNotes?: string | null;
  inspectorName?: string | null;
  inspectorTitle?: string | null;
  inspectorPhone?: string | null;
  inspectorEmail?: string | null;
  inspectorNotes?: string | null;
  titleName?: string | null;
  titleTitle?: string | null;
  titlePhone?: string | null;
  titleEmail?: string | null;
  titleNotes?: string | null;
  attorneyName?: string | null;
  attorneyTitle?: string | null;
  attorneyPhone?: string | null;
  attorneyEmail?: string | null;
  attorneyNotes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property_select".
 */
export interface PropertySelect<T extends boolean = true> {
  address?: T;
  mlsNumber?: T;
  status?: T;
  offerPrice?: T;
  listPrice?: T;
  sqft?: T;
  beds?: T;
  bathsFull?: T;
  bathsHalf?: T;
  annualTaxes?: T;
  listingDescription?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  heroImages?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  laName?: T;
  laTitle?: T;
  laPhone?: T;
  laEmail?: T;
  laNotes?: T;
  baName?: T;
  baTitle?: T;
  baPhone?: T;
  baEmail?: T;
  baNotes?: T;
  lenderName?: T;
  lenderTitle?: T;
  lenderPhone?: T;
  lenderEmail?: T;
  lenderNotes?: T;
  inspectorName?: T;
  inspectorTitle?: T;
  inspectorPhone?: T;
  inspectorEmail?: T;
  inspectorNotes?: T;
  titleName?: T;
  titleTitle?: T;
  titlePhone?: T;
  titleEmail?: T;
  titleNotes?: T;
  attorneyName?: T;
  attorneyTitle?: T;
  attorneyPhone?: T;
  attorneyEmail?: T;
  attorneyNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}